// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n=Integer.parseInt(args[0]);
			double minus=0;
			double plus=0;
			for(int i=0;i<=n;i++)
			{
			    double randomNumber = Math.random();
					if (randomNumber>=0.5)
					{
						plus++;
					}
					else{ minus--;}
			}
			System.out.println("> 0.5:"+ minus+" times");
			System.out.println("<= 0.5:"+ plus+" times");
			System.out.println("Ratio:"+minus/plus);
	}
}
